package com.sifast.model;

// Generated 16 mars 2015 12:37:03 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "Admin", schema = "dbo", catalog = "reclamation")
public class Admin implements java.io.Serializable {

	/**
	 * G�n�rer serial version ID
	 */
	private static final long serialVersionUID = -7431996371944075303L;
	private int idUtilisateur;
	private String nom;
	private String prenom;
	private String email;
	private String login;
	private String motPass;

	public Admin() {
	}

	public Admin(int idUtilisateur, String prenom, String email, String login, String motPass) {
		this.idUtilisateur = idUtilisateur;
		this.prenom = prenom;
		this.email = email;
		this.login = login;
		this.motPass = motPass;
	}

	public Admin(int idUtilisateur, String nom, String prenom, String email, String login, String motPass) {
		this.idUtilisateur = idUtilisateur;
		this.nom = nom;
		this.prenom = prenom;
		this.email = email;
		this.login = login;
		this.motPass = motPass;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "idUtilisateur", unique = true, nullable = false)
	public int getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(int idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	@Column(name = "nom", length = 15)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", nullable = false, length = 15)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "email", nullable = false, length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "login", nullable = false, length = 15)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "motPass", nullable = false, length = 15)
	public String getMotPass() {
		return this.motPass;
	}

	public void setMotPass(String motPass) {
		this.motPass = motPass;
	}
}