package com.sifast.model;

// Generated 16 mars 2015 12:37:03 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Institution generated by hbm2java
 */
@Entity
@Table(name = "Institution", schema = "dbo", catalog = "reclamation")
public class Institution implements java.io.Serializable {

	/**
	 * G�n�rer serial version ID
	 */
	private static final long serialVersionUID = 5951484243818057975L;
	private String nomInstit;
	private int telInstit;
	private Integer faxInstit;
	private String mailInstit;
	private String ipServeur;
	private Set<Agent> agents = new HashSet<Agent>(0);
	private Set<TypeReclamation> typeReclamations = new HashSet<TypeReclamation>(0);

	public Institution() {
	}

	public Institution(String nomInstit, int telInstit, String mailInstit) {
		this.nomInstit = nomInstit;
		this.telInstit = telInstit;
		this.mailInstit = mailInstit;
	}

	public Institution(String nomInstit, int telInstit, Integer faxInstit, String mailInstit, String ipServeur, Set<Agent> agents,
			Set<TypeReclamation> typeReclamations) {
		this.nomInstit = nomInstit;
		this.telInstit = telInstit;
		this.faxInstit = faxInstit;
		this.mailInstit = mailInstit;
		this.ipServeur = ipServeur;
		this.agents = agents;
		this.typeReclamations = typeReclamations;
	}

	@Id
	@Column(name = "nomInstit", unique = true, nullable = false, length = 50)
	public String getNomInstit() {
		return this.nomInstit;
	}

	public void setNomInstit(String nomInstit) {
		this.nomInstit = nomInstit;
	}

	@Column(name = "telInstit", nullable = false)
	public int getTelInstit() {
		return this.telInstit;
	}

	public void setTelInstit(int telInstit) {
		this.telInstit = telInstit;
	}

	@Column(name = "faxInstit")
	public Integer getFaxInstit() {
		return this.faxInstit;
	}

	public void setFaxInstit(Integer faxInstit) {
		this.faxInstit = faxInstit;
	}

	@Column(name = "mailInstit", nullable = false, length = 30)
	public String getMailInstit() {
		return this.mailInstit;
	}

	public void setMailInstit(String mailInstit) {
		this.mailInstit = mailInstit;
	}

	@Column(name = "ipServeur", length = 15)
	public String getIpServeur() {
		return this.ipServeur;
	}

	public void setIpServeur(String ipServeur) {
		this.ipServeur = ipServeur;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "institution")
	public Set<Agent> getAgents() {
		return this.agents;
	}

	public void setAgents(Set<Agent> agents) {
		this.agents = agents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "institution")
	public Set<TypeReclamation> getTypeReclamations() {
		return this.typeReclamations;
	}

	public void setTypeReclamations(Set<TypeReclamation> typeReclamations) {
		this.typeReclamations = typeReclamations;
	}

}
