package com.sifast.model;

// Generated 16 mars 2015 12:37:03 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reclamation generated by hbm2java
 */
@Entity
@Table(name = "Reclamation", schema = "dbo", catalog = "reclamation")
public class Reclamation implements java.io.Serializable {

	/**
	 * G�n�rer serial version ID
	 */
	private static final long serialVersionUID = 557521475010172852L;
	private int idReclam;
	private Client client;
	private TypeReclamation typeReclamation;
	private String refReclam;
	private boolean etatReclam;
	private boolean etatEnvoi;
	private double longitude;
	private double latitude;
	private String adresseAnomalie;
	private String autresPrecisions;
	private Date dateReclam;

	public Reclamation() {
	}

	public Reclamation(int idReclam, Client client, TypeReclamation typeReclamation, String refReclam, boolean etatReclam, boolean etatEnvoi, double longitude, double latitude,
			Date dateReclam) {
		this.idReclam = idReclam;
		this.client = client;
		this.typeReclamation = typeReclamation;
		this.refReclam = refReclam;
		this.etatReclam = etatReclam;
		this.etatEnvoi = etatEnvoi;
		this.longitude = longitude;
		this.latitude = latitude;
		this.dateReclam = dateReclam;
	}

	public Reclamation(int idReclam, Client client, TypeReclamation typeReclamation, String refReclam, boolean etatReclam, boolean etatEnvoi, double longitude, double latitude,
			String adresseAnomalie, String autresPrecisions, Date dateReclam) {
		this.idReclam = idReclam;
		this.client = client;
		this.typeReclamation = typeReclamation;
		this.refReclam = refReclam;
		this.etatReclam = etatReclam;
		this.etatEnvoi = etatEnvoi;
		this.longitude = longitude;
		this.latitude = latitude;
		this.adresseAnomalie = adresseAnomalie;
		this.autresPrecisions = autresPrecisions;
		this.dateReclam = dateReclam;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "idReclam", unique = true, nullable = false)
	public int getIdReclam() {
		return this.idReclam;
	}

	public void setIdReclam(int idReclam) {
		this.idReclam = idReclam;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idClientFK", nullable = false)
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idTypeRecFK", nullable = false)
	public TypeReclamation getTypeReclamation() {
		return this.typeReclamation;
	}

	public void setTypeReclamation(TypeReclamation typeReclamation) {
		this.typeReclamation = typeReclamation;
	}

	@Column(name = "refReclam", nullable = false, length = 20)
	public String getRefReclam() {
		return this.refReclam;
	}

	public void setRefReclam(String refReclam) {
		this.refReclam = refReclam;
	}

	@Column(name = "etatReclam", nullable = false)
	public boolean isEtatReclam() {
		return this.etatReclam;
	}

	public void setEtatReclam(boolean etatReclam) {
		this.etatReclam = etatReclam;
	}
	
	@Column(name = "etatEnvoi", nullable = false)
	public boolean isEtatEnvoi() {
		return this.etatEnvoi;
	}

	public void setEtatEnvoi(boolean etatEnvoi) {
		this.etatEnvoi = etatEnvoi;
	}

	@Column(name = "longitude", nullable = false, precision = 53, scale = 0)
	public double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "latitude", nullable = false, precision = 53, scale = 0)
	public double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "adresseAnomalie", length = 50)
	public String getAdresseAnomalie() {
		return this.adresseAnomalie;
	}

	public void setAdresseAnomalie(String adresseAnomalie) {
		this.adresseAnomalie = adresseAnomalie;
	}

	@Column(name = "autresPrecisions", length = 50)
	public String getAutresPrecisions() {
		return this.autresPrecisions;
	}

	public void setAutresPrecisions(String autresPrecisions) {
		this.autresPrecisions = autresPrecisions;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateReclam", nullable = false, length = 10)
	public Date getDateReclam() {
		return this.dateReclam;
	}

	public void setDateReclam(Date dateReclam) {
		this.dateReclam = dateReclam;
	}

}
